### ISSUE TITLE
Unable to resolve the request "sitemap/init"

### ISSUE THREAD

**Issue by MaximBelyaev** [wdmg/yii2-sitemap#1]
After trying to run _php yii sitemap/init_ in console I'm getting:
Unable to resolve the request "sitemap/init"

**Comment by alex-wdmg** [comment]
You configured the module in `/config/console.php` ?

To add a module to the project, add the following data in your configuration file:

    'modules' => [
        ...
        'sitemap' => [
            'class' => 'wdmg\sitemap\Module',
            'routePrefix' => 'admin',
            'supportModels'  => [  // list of supported models for displaying a sitemap
                'pages' => 'wdmg\pages\models\Pages',
                'news' => 'wdmg\news\models\News',
            ],
            'cacheExpire' => 43200, // sitemap cache lifetime, `0` - for not use cache
            'defaultFrequency' => 'weekly', // default update frequency
            'defaultPriority' => 0.5, // default update priority
            'sitemapRoute' => '/' // default route to rendered sitemap.xml (use "/" - for root)
        ],
        ...
    ],
